<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Himanshusingh01" name="GET_1" tests="2" failures="1" timestamp="1 Nov 2019 10:18:31 GMT" time="8.939" errors="0">
  <testcase name="checkGET" time="2.38" classname="com.RestAssured.testCases.GET_1_Test"/>
  <testcase name="checkGETbyID" time="0.003" classname="com.RestAssured.testCases.GET_2_Test">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.RestAssured.testCases.GET_2_Test.checkGETbyID(GET_2_Test.java:27)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- checkGETbyID -->
</testsuite> <!-- GET_1 -->
